In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [ [1, 2, 3], [4, 5, 6], [7, 8 ,9]]

In [5]:
np.array(my_matrix) 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# create numbers sequence
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
arr = np.zeros((3,3))

In [11]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
arr = np.ones((3,3))

In [13]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [16]:
np.random.rand(5) 

array([0.50363271, 0.08105111, 0.25019109, 0.90346171, 0.92126888])

In [17]:
np.random.rand(6) * 100

array([88.63825649, 13.73504592, 58.53755076, 57.23271548, 39.39120275,
       47.83478732])

In [18]:
np.random.rand(5, 3, 2)

array([[[0.61290495, 0.31064086],
        [0.86670371, 0.5248412 ],
        [0.78246905, 0.31453686]],

       [[0.55501413, 0.23301372],
        [0.15605165, 0.46475582],
        [0.90415624, 0.10645442]],

       [[0.88981365, 0.09464848],
        [0.77061191, 0.88051342],
        [0.0488115 , 0.17257069]],

       [[0.0085771 , 0.30948812],
        [0.37610904, 0.82962274],
        [0.53908344, 0.77130109]],

       [[0.78734148, 0.58999125],
        [0.37774758, 0.23467839],
        [0.92548789, 0.10909715]]])

In [20]:
# gaussian
np.random.randn(4)

array([-0.05164578, -0.88891138,  0.45129178, -0.74260377])

In [21]:
np.random.randint(0, 100, 10)

array([88, 31, 28, 78, 17, 68, 77, 20, 17, 79])

In [22]:
arr = np.random.rand(25)

In [23]:
arr

array([0.86555233, 0.37225045, 0.39692673, 0.64768058, 0.10523867,
       0.22444591, 0.73989585, 0.62478786, 0.30565591, 0.89296948,
       0.87363486, 0.54416217, 0.81351462, 0.94909027, 0.2658729 ,
       0.61885567, 0.2483028 , 0.39966263, 0.47158977, 0.88800449,
       0.52371432, 0.75645011, 0.26772341, 0.81535051, 0.38112897])

In [25]:
arr1 = arr.reshape((5, 5))

In [26]:
arr1

array([[0.86555233, 0.37225045, 0.39692673, 0.64768058, 0.10523867],
       [0.22444591, 0.73989585, 0.62478786, 0.30565591, 0.89296948],
       [0.87363486, 0.54416217, 0.81351462, 0.94909027, 0.2658729 ],
       [0.61885567, 0.2483028 , 0.39966263, 0.47158977, 0.88800449],
       [0.52371432, 0.75645011, 0.26772341, 0.81535051, 0.38112897]])

In [27]:
arr1.shape

(5, 5)

In [28]:
arr.shape

(25,)

In [29]:
arr1.argmax()

13