In [1]:
import numpy as np

In [5]:
arr = np.arange(0,30,3)

In [6]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [3]:
arr[3]

9

In [4]:
arr[2:5]

array([ 6,  9, 12])

In [7]:
arr[:5]

array([ 0,  3,  6,  9, 12])

In [8]:
arr[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [9]:
arr[2:] = 100

In [10]:
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

In [13]:
#  bidimensional array
arr = np.arange(50).reshape((5,10))

In [14]:
arr.shape

(5, 10)

In [18]:
arr[:2][:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [17]:
arr[:][:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [19]:
arr2 = arr[:3]

In [20]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [21]:
arr2[:] = 100

In [22]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [23]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [24]:
arr2 = arr[:3].copy()

In [25]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [26]:
arr[1:4,5:]

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 35,  36,  37,  38,  39]])

In [27]:
arr > 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [29]:
arr[arr > 30]

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49])

In [30]:
array = np.linspace(0, 100, 30)

In [31]:
array = array.reshape(3, 10)

In [32]:
array

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [33]:
array[0:2, 2]

array([ 6.89655172, 41.37931034])

In [34]:
array[:, 2]

array([ 6.89655172, 41.37931034, 75.86206897])

In [35]:
np.sqrt(array)

array([[ 0.        ,  1.85695338,  2.62612866,  3.2163376 ,  3.71390676,
         4.15227399,  4.54858826,  4.91303684,  5.25225731,  5.57086015],
       [ 5.8722022 ,  6.15881762,  6.43267521,  6.69534063,  6.94808334,
         7.19194952,  7.42781353,  7.65641493,  7.87838597,  8.09427213],
       [ 8.30454799,  8.50962943,  8.70988341,  8.90563557,  9.09717652,
         9.28476691,  9.46864153,  9.64901281,  9.82607369, 10.        ]])

In [36]:
np.exp(array)

array([[1.00000000e+00, 3.14461281e+01, 9.88858971e+02, 3.10957859e+04,
        9.77842065e+05, 3.07493468e+07, 9.66947898e+08, 3.04067675e+10,
        9.56175104e+11, 3.00680048e+13],
       [9.45522330e+14, 2.97330163e+16, 9.34988238e+17, 2.94017599e+19,
        9.24571508e+20, 2.90741940e+22, 9.14270830e+23, 2.87502776e+25,
        9.04084912e+26, 2.84299699e+28],
       [8.94012476e+29, 2.81132308e+31, 8.84052257e+32, 2.78000205e+34,
        8.74203006e+35, 2.74902997e+37, 8.64463485e+38, 2.71840295e+40,
        8.54832473e+41, 2.68811714e+43]])